### PR TITLE
Detect ipaddr

### PR DESCRIPTION
**Pull request by FedericoCeratto**

### CODE REVIEW

**Comment by ThomasTJdev** [comment]
Hi @FedericoCeratto 

I like it - it looks good! Are you planning to split the `*.cfg`-file per module for `-d:release`? 
```nim
    # nimhapkg/resources/utils/common.nim - loadConf()
    if modulename == "":
      fn = "/etc/nimha/nimha.cfg"
    else:
      fn = "/etc/nimha/" & modulename & ".cfg"
```

How would you like the review process? Should I do continuously reviewing or will you ping me? We can also make a devel/refactor branch, which defines the next release.

**Comment by FedericoCeratto** [comment]
@ThomasTJdev this PR is meant to go on top of #30 - the config refactor is in there. This one is to move away from ifconfig.

**Comment by FedericoCeratto** [comment]
@ThomasTJdev I can create PRs in dedicated branches or otherwise as you prefer. The PRs are ready for review (unless stated otherwise).

**Comment by ThomasTJdev** [comment]
> @ThomasTJdev I can create PRs in dedicated branches or otherwise as you prefer. The PRs are ready for review (unless stated otherwise).

@FedericoCeratto PR's on top is fine by me. If you going for a larger refactor, you may create a dedicated branch for that. I'll review the *new* commits in each PR.

**Comment by FedericoCeratto** [comment]
@ThomasTJdev this is now one commit only and is ready for review.

**Pull request merged**
